name: taxi_rahmati
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^2.0.1 # service locator
  flutter_bloc: ^0.21.0 # block for state management
  equatable: ^0.4.0 # value equality
  dartz: ^0.8.6 # functional programming
  connectivity: ^0.4.3+7 # remote api
  http: ^0.12.0+2 # "
  shared_preferences: ^0.5.3+4 # local cache
  decimal: ^2.2.0 # for currency
  uuid: ^3.0.6 # id generation
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: 

flutter:
  uses-material-design: true